#!/usr/bin/env python3.5

# toy script test

import os
import re
import subprocess

path = '/Users/morgan/Documents/COMPTEL/COMPTEL_data'

for dirName, subdirList, fileList in os.walk(path):
    print(dirName)
    if not subdirList:
        print('None yall')
    print(subdirList)
    print(fileList)
    print('\n')
